const CACHE_NAME = "mompy-v158";
const FILES = [
  "./",
  "./index.html",
  "./css/styles.css?v=127",
  "./css/typography.css?v=5",
  "./js/content-i18n.js?v=1",
  "./js/app.js?v=125",
  "./manifest.webmanifest",
  "./assets/grade.png",
  "./assets/grade_entrada.png",
  "./assets/mompy_loading_base.png",
  "./assets/mompy_boot_title.png?v=1",
  "./assets/hepterakt_boot_monitor.png",
  "./assets/mompy_idle.ico",
  "./assets/mompy_idle.png?v=2",
  "./assets/mompy_look_side.png",
  "./assets/mompy_talk_1.png",
  "./assets/mompy_talk_2.png",
  "./assets/mompy_happy.png",
  "./assets/mompy_sad.png",
  "./assets/mompy_front.png?v=5",
  "./assets/mompy_gaze_transition.png?v=1",
  "./assets/mompy_front_blink.png?v=1",
  "./assets/mompy_achievements.png?v=1",
  "./assets/mompy_settings.png?v=1",
  "./assets/settings-panel/settings-panel-base.png?v=1",
  "./assets/settings-panel/settings-gear-large.png?v=1",
  "./assets/settings-panel/settings-gear-medium.png?v=1",
  "./assets/settings-panel/settings-gear-small.png?v=1",
  "./assets/start-buttons/start-button-frame.png?v=1",
  "./assets/start-buttons/continue-button-frame.png?v=1",
  "./assets/ui-icons/achievements-star.png?v=1",
  "./assets/ui-icons/game-flag.png?v=1",
  "./assets/ui-icons/settings-gear.png?v=1",
  "./assets/ui-icons/user-profile.png?v=1",
  "./assets/ui-icons/level-progress.png?v=1",
  "./assets/ui-icons/missions-completed.png?v=1",
  "./assets/panels/card-small.png?v=3",
  "./assets/panels/card-medium.png?v=1",
  "./assets/panels/panel-large.png?v=3",
  "./assets/panels/panel-section.png?v=3",
  "./assets/reward-capsule/capsule-frame-01-closed.png?v=1",
  "./assets/reward-capsule/capsule-frame-02-unlocking.png?v=1",
  "./assets/reward-capsule/capsule-frame-03-opening.png?v=1",
  "./assets/reward-capsule/capsule-frame-04-open.png?v=1",
  "./assets/reward-capsule/reward-monitor-frame.png?v=1",
  "./assets/reward-capsule/legendary-capsule-stages.png?v=1",
  "./assets/controls/button-frames/button-primary-normal.png?v=1",
  "./assets/controls/button-frames/button-primary-hover.png?v=1",
  "./assets/controls/button-frames/button-primary-pressed.png?v=1",
  "./assets/controls/button-frames/button-primary-disabled.png?v=1",
  "./assets/controls/button-frames/button-secondary-normal.png?v=1",
  "./assets/controls/button-frames/button-secondary-hover.png?v=1",
  "./assets/controls/button-frames/button-secondary-pressed.png?v=1",
  "./assets/controls/button-frames/button-secondary-disabled.png?v=1",
  "./assets/controls/button-frames/button-danger-normal.png?v=1",
  "./assets/controls/button-frames/button-danger-hover.png?v=1",
  "./assets/controls/button-frames/button-danger-pressed.png?v=1",
  "./assets/controls/button-frames/button-danger-disabled.png?v=1",
  "./assets/controls/prepared/button-icon-frame.png?v=1",
  "./assets/controls/prepared/button-tab-frame.png?v=1",
  "./assets/controls/prepared/button-nav-horizontal.png?v=1",
  "./assets/controls/prepared/toggle-off-frame.png?v=1",
  "./assets/controls/prepared/toggle-on-frame.png?v=1",
  "./assets/mompy_celebrate.png",
  "./assets/mompy_shutdown.png",
  "./assets/audio/achievement-rail-arrive.wav?v=1",
  "./assets/audio/achievement-glass-descend.wav?v=1",
  "./assets/audio/achievement-content-reveal.wav?v=1",
  "./assets/audio/settings-gear-engage.wav?v=1",
  "./assets/audio/settings-gears-turn.wav?v=1",
  "./assets/audio/settings-panel-lock.wav?v=1",
  "./assets/achievements/achievement-star-terminal.png",
  "./assets/achievements/achievement-sinal-de-retorno.png?v=1",
  "./assets/achievements/achievement-tres-dias-online.png?v=1",
  "./assets/achievements/achievement-sequencia-inicial-turquoise.png?v=1",
  "./assets/achievements/achievement-semana-de-codigo-turquoise.png?v=1",
  "./assets/achievements/achievement-semana-sem-desligar-blue.png?v=1",
  "./assets/achievements/achievement-operador-frequente-blue.png?v=1",
  "./assets/achievements/achievement-mes-no-console-purple.png?v=1",
  "./assets/achievements/achievement-sinal-trimestral-purple.png?v=1",
  "./assets/achievements/achievement-semestre-programacao-gold.png?v=1",
  "./assets/achievements/achievement-companheiro-do-mompy-gold.png?v=1",
  "./assets/achievements/achievement-glass-panel.png?v=1",
  "./assets/achievements/achievement-metal-rail.png?v=1",
  "./assets/achievements/python/achievement-python-console-frame-01.png?v=1",
  "./assets/achievements/python/achievement-python-console-frame-02.png?v=1",
  "./assets/achievements/python/achievement-python-console-frame-03.png?v=1",
  "./assets/achievements/python/achievement-python-variables.png?v=1",
  "./assets/achievements/python/achievement-python-branches.png?v=1",
  "./assets/achievements/python/achievement-python-loops.png?v=1",
  "./assets/achievements/python/achievement-python-lists.png?v=1",
  "./assets/achievements/python/achievement-python-math.png?v=1",
  "./assets/achievements/python/achievement-python-functions.png?v=1",
  "./assets/achievements/python/achievement-python-while.png?v=1",
  "./assets/achievements/python/achievement-python-debug.png?v=1",
  "./assets/achievements/python/achievement-python-master.png?v=1",
  "./assets/desligando5.png",
  "./assets/desligando2.png",
  "./assets/desligando3.png",
  "./assets/desligando4.png",
  "./assets/audio/click.wav",
  "./assets/audio/run.wav",
  "./assets/audio/success.wav",
  "./assets/audio/error.wav",
  "./assets/audio/shutdown.wav",
  "./assets/audio/mompy_crt_ambient_loop_minimal.wav",
  "./assets/name_mompy.png",
  "./assets/hepter_studios_boot_logo_green.png?v=3",
  "./assets/loading/mompy-run-01.png?v=2",
  "./assets/loading/mompy-run-02-v3.png?v=1",
  "./assets/loading/mompy-run-03-v3.png?v=1",
  "./assets/loading/mompy-run-04-v3.png?v=1",
  "./assets/loading/mompy-run-05.png?v=2",
  "./assets/settings.svg",
  "./assets/fonts/PixelOperator-Regular.ttf",
  "./assets/fonts/PixelOperator-Bold.ttf",
  "./assets/fonts/PixelOperatorMono-Regular.ttf",
  "./assets/fonts/PixelOperatorMono-Bold.ttf",
  "./assets/fonts/PixelOperator-LICENSE.txt",
  "./assets/square-arrow-up-left.svg",
  "./assets/square-arrow-down-right.svg",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(FILES))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request)),
  );
});
