"""Mission catalog for Mompy.

The learning path is ordered for complete beginners. Each block introduces one
new family of concepts, and missions only ask for concepts already covered by
the guided lesson for that block.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass


PLANNED_TOTAL_MISSIONS = 30


@dataclass(frozen=True)
class Mission:
    id: str
    number: int
    level: int
    block: int
    title: str
    concept: str
    description: str
    objective: str
    starter_code: str
    expected_output: str
    help: str
    expected_concepts: tuple[str, ...]
    xp: int

    def to_dict(self) -> dict:
        data = asdict(self)
        data["expected_concepts"] = list(self.expected_concepts)
        data["starterCode"] = self.starter_code
        data["expectedOutput"] = self.expected_output
        return data


def mission_xp(level: int) -> int:
    """Return progressive mission XP without making early levels too fast."""
    return 35 + max(0, level - 1) * 5


MISSIONS: tuple[Mission, ...] = (
    Mission(
        id="mission_001",
        number=1,
        level=1,
        block=1,
        title="Mission 01 - First Output",
        concept="print",
        description="First step: make the program write a message to the console.",
        objective="Use print() to show exactly: Hello, Mompy!",
        starter_code="# write here\n",
        expected_output="Hello, Mompy!",
        help='Use quotes inside print: print("Hello, Mompy!")',
        expected_concepts=("print", "string", "quotes", "parentheses"),
        xp=mission_xp(1),
    ),
    Mission(
        id="mission_002",
        number=2,
        level=2,
        block=1,
        title="Mission 02 - Text",
        concept="strings",
        description="Text in Python goes inside quotes.",
        objective="Show exactly: Python",
        starter_code="# text needs quotes\n",
        expected_output="Python",
        help='Write the text inside quotes inside print().',
        expected_concepts=("print", "string", "quotes"),
        xp=mission_xp(2),
    ),
    Mission(
        id="mission_003",
        number=3,
        level=3,
        block=1,
        title="Mission 03 - Parentheses",
        concept="print parentheses",
        description="Commands like print use parentheses to receive information.",
        objective="Show exactly: Boot ready",
        starter_code="# print needs opening and closing parentheses\n",
        expected_output="Boot ready",
        help='Use print("Boot ready"). Check quotes and parentheses.',
        expected_concepts=("print", "string", "quotes", "parentheses"),
        xp=mission_xp(3),
    ),
    Mission(
        id="mission_004",
        number=4,
        level=4,
        block=1,
        title="Mission 04 - Another Message",
        concept="output",
        description="The console output shows the text the program wrote.",
        objective="Show exactly: Mompy",
        starter_code="# show a simple message\n",
        expected_output="Mompy",
        help='Use print("Mompy"). Don\'t forget the quotes.',
        expected_concepts=("print", "string", "output"),
        xp=mission_xp(4),
    ),
    Mission(
        id="mission_005",
        number=5,
        level=5,
        block=1,
        title="Mission 05 - Two Lines",
        concept="two print calls",
        description="You can use more than one command, one per line.",
        objective="Show First and then Second, each on its own line.",
        starter_code="# use two prints\n",
        expected_output="First\nSecond",
        help='Use two commands: print("First") and print("Second").',
        expected_concepts=("print", "string", "multiple commands", "output"),
        xp=mission_xp(5),
    ),
    Mission(
        id="mission_006",
        number=6,
        level=6,
        block=2,
        title="Mission 06 - Variable",
        concept="variables",
        description="Variables store values for you to use later.",
        objective='Create name = "Mompy" and then show name with print().',
        starter_code='name = "Mompy"\n',
        expected_output="Mompy",
        help='After creating the variable, use print(name). Do not put name in quotes inside print.',
        expected_concepts=("variable", "assignment", "print", "string"),
        xp=mission_xp(6),
    ),
    Mission(
        id="mission_007",
        number=7,
        level=7,
        block=2,
        title="Mission 07 - Number Value",
        concept="numbers",
        description="Variables can also store numbers.",
        objective="Create level = 1 and show level.",
        starter_code="level = 1\n",
        expected_output="1",
        help="Use print(level). Numbers don't need quotes.",
        expected_concepts=("variable", "assignment", "number", "print"),
        xp=mission_xp(7),
    ),
    Mission(
        id="mission_008",
        number=8,
        level=8,
        block=2,
        title="Mission 08 - Change Value",
        concept="reassignment",
        description="A variable can receive a new value later.",
        objective='Start with mode = "off", change it to "on" and show mode.',
        starter_code='mode = "off"\n',
        expected_output="on",
        help='Assign mode = "on" before using print(mode).',
        expected_concepts=("variable", "assignment", "reassignment", "print"),
        xp=mission_xp(8),
    ),
    Mission(
        id="mission_009",
        number=9,
        level=9,
        block=2,
        title="Mission 09 - Simple Sum",
        concept="addition",
        description="Python can add numbers stored in variables.",
        objective="Add a and b to show 5.",
        starter_code="a = 2\nb = 3\n",
        expected_output="5",
        help="Use print(a + b).",
        expected_concepts=("variable", "number", "addition", "print"),
        xp=mission_xp(9),
    ),
    Mission(
        id="mission_010",
        number=10,
        level=10,
        block=2,
        title="Mission 10 - Text Variable",
        concept="string variable",
        description="When a variable stores text, print shows the stored text.",
        objective='Store "Ready" in message and show message.',
        starter_code='message = "Ready"\n',
        expected_output="Ready",
        help="Use print(message), without quotes around message.",
        expected_concepts=("variable", "string", "assignment", "print"),
        xp=mission_xp(10),
    ),
    Mission(
        id="mission_011",
        number=11,
        level=11,
        block=3,
        title="Mission 11 - If True",
        concept="if",
        description="The if block runs when the condition is true.",
        objective="Use if to show exactly: Ready",
        starter_code="power = True\n",
        expected_output="Ready",
        help='Use if power: and inside it, print("Ready").',
        expected_concepts=("if", "boolean", "colon", "indentation", "print"),
        xp=mission_xp(11),
    ),
    Mission(
        id="mission_012",
        number=12,
        level=12,
        block=3,
        title="Mission 12 - Greater Than",
        concept="comparison",
        description="Comparisons produce True or False for if to decide.",
        objective="If temperature is greater than 5, show Warm.",
        starter_code="temperature = 10\n",
        expected_output="Warm",
        help='Use if temperature > 5: and inside it print("Warm").',
        expected_concepts=("if", "comparison", "greater than", "indentation"),
        xp=mission_xp(12),
    ),
    Mission(
        id="mission_013",
        number=13,
        level=13,
        block=3,
        title="Mission 13 - Equality",
        concept="equality",
        description="Use == to compare values. = stores a value; == compares.",
        objective='If code equals "py", show Python.',
        starter_code='code = "py"\n',
        expected_output="Python",
        help='Use if code == "py": and inside it print("Python").',
        expected_concepts=("if", "equality", "==", "string", "indentation"),
        xp=mission_xp(13),
    ),
    Mission(
        id="mission_014",
        number=14,
        level=14,
        block=3,
        title="Mission 14 - Else",
        concept="else",
        description="else runs when the if condition is not true.",
        objective="With score = 1, show Try again using if and else.",
        starter_code="score = 1\n",
        expected_output="Try again",
        help='Use if score >= 2: for Pass and else: for print("Try again").',
        expected_concepts=("if", "else", "comparison", "indentation"),
        xp=mission_xp(14),
    ),
    Mission(
        id="mission_015",
        number=15,
        level=15,
        block=3,
        title="Mission 15 - Less Or Equal",
        concept="less or equal",
        description="Comparisons like <= also help the program decide.",
        objective="If count is less than or equal to 3, show Inside.",
        starter_code="count = 3\n",
        expected_output="Inside",
        help='Use if count <= 3: and inside it print("Inside").',
        expected_concepts=("if", "comparison", "<=", "indentation"),
        xp=mission_xp(15),
    ),
    Mission(
        id="mission_016",
        number=16,
        level=16,
        block=4,
        title="Mission 16 - Range Loop",
        concept="for range",
        description="for with range repeats a block for a sequence of numbers.",
        objective="Use range(3) to show 0, 1 and 2.",
        starter_code="for i in range(3):\n    ",
        expected_output="0\n1\n2",
        help="Inside the for, use print(i). The print line must be indented.",
        expected_concepts=("for", "range", "loop variable", "indentation", "print"),
        xp=mission_xp(16),
    ),
    Mission(
        id="mission_017",
        number=17,
        level=17,
        block=4,
        title="Mission 17 - Repeat Text",
        concept="repeat text",
        description="The block inside for runs once for each iteration.",
        objective="Show Mompy twice using for and range.",
        starter_code="for i in range(2):\n    ",
        expected_output="Mompy\nMompy",
        help='Inside the for, use print("Mompy").',
        expected_concepts=("for", "range", "indentation", "print"),
        xp=mission_xp(17),
    ),
    Mission(
        id="mission_018",
        number=18,
        level=18,
        block=4,
        title="Mission 18 - Start At One",
        concept="range start stop",
        description="range can receive a start and a stop.",
        objective="Use range(1, 4) to show 1, 2 and 3.",
        starter_code="for number in range(1, 4):\n    ",
        expected_output="1\n2\n3",
        help="Inside the for, use print(number).",
        expected_concepts=("for", "range", "loop variable", "print"),
        xp=mission_xp(18),
    ),
    Mission(
        id="mission_019",
        number=19,
        level=19,
        block=4,
        title="Mission 19 - Loop Letters",
        concept="string loop",
        description="for can also go through each letter of a string.",
        objective='Show the letters of "py", one per line.',
        starter_code='for letter in "py":\n    ',
        expected_output="p\ny",
        help="Inside the for, use print(letter).",
        expected_concepts=("for", "string sequence", "loop variable", "print"),
        xp=mission_xp(19),
    ),
    Mission(
        id="mission_020",
        number=20,
        level=20,
        block=4,
        title="Mission 20 - Loop Sum",
        concept="accumulator",
        description="A loop can update a variable on each iteration.",
        objective="Add 0, 1 and 2 with for and show 3.",
        starter_code="total = 0\nfor number in range(3):\n    ",
        expected_output="3",
        help="Inside the for, use total = total + number. After the for, use print(total).",
        expected_concepts=("for", "range", "variable update", "addition", "print"),
        xp=mission_xp(20),
    ),
    Mission(
        id="mission_021",
        number=21,
        level=21,
        block=5,
        title="Mission 21 - Create List",
        concept="lists",
        description="Lists store multiple values in order.",
        objective='Create a list with "onion", "terminal" and "python", then show the list.',
        starter_code="items = []\n",
        expected_output="['onion', 'terminal', 'python']",
        help='Use items = ["onion", "terminal", "python"] and print(items).',
        expected_concepts=("list", "brackets", "items", "commas", "print"),
        xp=mission_xp(21),
    ),
    Mission(
        id="mission_022",
        number=22,
        level=22,
        block=5,
        title="Mission 22 - List Index",
        concept="index",
        description="The first item in a list is at index 0.",
        objective="Show the second item in the list.",
        starter_code='items = ["onion", "terminal", "python"]\n',
        expected_output="terminal",
        help="The second item is items[1]. Use print(items[1]).",
        expected_concepts=("list", "index", "zero based index", "print"),
        xp=mission_xp(22),
    ),
    Mission(
        id="mission_023",
        number=23,
        level=23,
        block=5,
        title="Mission 23 - Append",
        concept="append",
        description="append adds an item to the end of a list.",
        objective="Add 4 to [1, 2, 3] and show the list.",
        starter_code="numbers = [1, 2, 3]\n",
        expected_output="[1, 2, 3, 4]",
        help="Use numbers.append(4), then print(numbers).",
        expected_concepts=("list", "append", "number", "print"),
        xp=mission_xp(23),
    ),
    Mission(
        id="mission_024",
        number=24,
        level=24,
        block=5,
        title="Mission 24 - Loop List",
        concept="iterate list",
        description="You can use for to go through each item in a list.",
        objective="Show each item in the list, one per line.",
        starter_code='items = ["onion", "python"]\n',
        expected_output="onion\npython",
        help="Use for item in items: and inside it print(item).",
        expected_concepts=("list", "for", "item", "indentation", "print"),
        xp=mission_xp(24),
    ),
    Mission(
        id="mission_025",
        number=25,
        level=25,
        block=5,
        title="Mission 25 - List Length",
        concept="len list",
        description="len counts how many items are in a list.",
        objective="Show how many numbers are in the list.",
        starter_code="numbers = [1, 2, 3]\n",
        expected_output="3",
        help="Use print(len(numbers)).",
        expected_concepts=("list", "len", "items", "print"),
        xp=mission_xp(25),
    ),
    Mission(
        id="mission_026",
        number=26,
        level=26,
        block=6,
        title="Mission 26 - Simple Function",
        concept="functions",
        description="A function stores a block of code under a name.",
        objective='Create say_hello() to show Hello and then call the function.',
        starter_code="def say_hello():\n    ",
        expected_output="Hello",
        help='Inside the function use print("Hello"). Then call say_hello().',
        expected_concepts=("def", "function", "call", "indentation", "print"),
        xp=mission_xp(26),
    ),
    Mission(
        id="mission_027",
        number=27,
        level=27,
        block=6,
        title="Mission 27 - Parameter",
        concept="parameters",
        description="A parameter is information that enters the function.",
        objective='Create greet(user) and call it with "Mompy" to show Hello, Mompy.',
        starter_code="def greet(user):\n    ",
        expected_output="Hello, Mompy",
        help='Use print("Hello, " + user) inside the function and then greet("Mompy").',
        expected_concepts=("def", "parameter", "call", "string concatenation", "print"),
        xp=mission_xp(27),
    ),
    Mission(
        id="mission_028",
        number=28,
        level=28,
        block=6,
        title="Mission 28 - Return",
        concept="return",
        description="return sends a value back to whoever called the function.",
        objective="Create add(a, b), return a + b and show add(2, 3).",
        starter_code="def add(a, b):\n    ",
        expected_output="5",
        help="The function should return a + b. Then use print(add(2, 3)).",
        expected_concepts=("def", "parameters", "return", "addition", "print"),
        xp=mission_xp(28),
    ),
    Mission(
        id="mission_029",
        number=29,
        level=29,
        block=6,
        title="Mission 29 - Return Text",
        concept="return text",
        description="A function can also return text.",
        objective='Create make_message(user) and show Hello, Mackson.',
        starter_code="def make_message(user):\n    ",
        expected_output="Hello, Mackson",
        help='Return "Hello, " + user and then use print(make_message("Mackson")).',
        expected_concepts=("def", "parameter", "return", "string concatenation", "print"),
        xp=mission_xp(29),
    ),
    Mission(
        id="mission_030",
        number=30,
        level=30,
        block=6,
        title="Mission 30 - Function Result",
        concept="function result",
        description="Functions help organize a small rule under a name.",
        objective="Create double(n), return n * 2 and show double(4).",
        starter_code="def double(n):\n    ",
        expected_output="8",
        help="Use return n * 2 inside the function. Then use print(double(4)).",
        expected_concepts=("def", "parameter", "return", "multiplication", "print"),
        xp=mission_xp(30),
    ),
)


MISSIONS_BY_ID: dict[str, Mission] = {mission.id: mission for mission in MISSIONS}


def get_mission(mission_id: str) -> Mission | None:
    return MISSIONS_BY_ID.get(mission_id)


def get_missions() -> list[dict]:
    return [mission.to_dict() for mission in MISSIONS]


def get_current_mission(index: int) -> Mission:
    if index < 0:
        return MISSIONS[0]
    if index >= len(MISSIONS):
        return MISSIONS[-1]
    return MISSIONS[index]
