"use strict";

// Rich, self-paced classroom lessons. Presentation logic lives in app.js so
// this file remains a content source that can be reviewed independently.
window.MOMPY_CLASSROOM_LESSONS = {
  briefing_001: {
    "pt-BR": {
      title: "Aula 1 — Conheça o Python",
      subtitle: "Conheça o Python e dê sua primeira instrução",
      estimatedMinutes: 20,
      steps: [
        {
          id: "opening",
          phase: "AULA 1",
          type: "lesson",
          title: "Conheça o Python e dê sua primeira instrução",
          body: ["Hoje você vai entender o que é Python e fazer uma máquina responder pela primeira vez."],
          bullets: ["descobrir o que é Python", "conhecer sua origem", "mostrar sua primeira mensagem"],
          mompy: "Vamos começar do zero. Você não precisa saber programação ainda.",
          mompyVisible: true,
          actionLabel: "COMEÇAR",
          actionOnMompy: true,
        },
        {
          id: "what-is-python",
          phase: "PARTE 1 · CONHEÇA O PYTHON",
          type: "lesson",
          title: "O que é Python?",
          lead: "Python é uma linguagem de programação.",
          body: [
            "Com ela, escrevemos instruções que o computador consegue executar.",
            "Uma linguagem de programação dá nomes e regras para transformar uma ideia humana em passos exatos. Esses passos escritos formam o código.",
            "Nesta aula, você seguirá esse caminho desde a origem do Python até uma primeira instrução completa.",
            "Exemplo conceitual: “mostrar uma mensagem” é a ideia; o código será a instrução precisa que o computador poderá executar.",
          ],
          definition: "Linguagem de programação é um conjunto de nomes e regras usado para escrever instruções que um computador pode executar.",
          mentalModel: "IDEIA HUMANA → PASSOS EXATOS → CÓDIGO",
          note: "Ainda não precisamos decorar código. Primeiro vamos entender a identidade do Python; depois veremos quem lê as instruções e quais regras organizam sua escrita.",
          mompy: "Programar é explicar com precisão o que a máquina deve fazer.",
          mompyVisible: true,
          aux: {
            kind: "idea-code",
            idea: "IDEIA",
            arrow: "→",
            code: "CÓDIGO",
            subtitle: "PASSOS EXATOS PARA A MÁQUINA",
            steps: [
              "RECEBER IDEIA DO HUMANO",
              "QUEBRAR EM PASSOS LÓGICOS",
              "ESCREVER INSTRUÇÕES PRECISAS",
              "EXECUTAR SEM AMBIGUIDADE",
            ],
            duration: 24000,
            alt: "Uma ideia humana sendo transformada em código por etapas",
          },
        },
        {
          id: "guido",
          phase: "PARTE 1 · CONHEÇA O PYTHON",
          type: "lesson",
          title: "Quem começou tudo?",
          body: [
            "Guido van Rossum começou Python em dezembro de 1989, como um projeto pessoal durante uma semana ao redor do Natal.",
            "Ele queria criar um sucessor da linguagem ABC que também tivesse apelo para pessoas acostumadas a Unix e C.",
          ],
          definition: "Sucessor, neste contexto, é uma nova linguagem pensada para continuar um caminho anterior: Python foi concebido como sucessor de ABC.",
          mompy: "A origem tem um objetivo concreto: partir do que já existia e construir uma nova linguagem. Agora vamos marcar quando ela se tornou pública.",
          mompyVisible: true,
          aux: {
            kind: "identity",
            label: "ARQUIVO DE ORIGEM",
            image: "./assets/classroom/guido-van-rossum-crt-v2.png?v=1",
            alt: "Retrato em pixel art de Guido van Rossum",
            title: "GUIDO VAN ROSSUM",
            subtitle: "CRIADOR DO PYTHON",
            facts: ["DEZ 1989", "ABC → PYTHON"],
          },
        },
        {
          id: "timeline",
          phase: "PARTE 1 · CONHEÇA O PYTHON",
          type: "lesson",
          title: "Uma história que cresceu",
          body: [
            "Depois do início em dezembro de 1989, Guido anunciou Python publicamente na Usenet em fevereiro de 1991.",
            "Hoje, a Python Software Foundation, ou PSF, detém os direitos do projeto.",
          ],
          definition: "PSF é a sigla de Python Software Foundation, organização que hoje detém os direitos do projeto.",
          note: "As datas dão contexto; você não precisa decorá-las.",
          mompy: "Guarde a sequência, não os números: projeto pessoal, anúncio público e uma fundação responsável pelos direitos do projeto.",
          mompyVisible: true,
          aux: {
            kind: "timeline",
            label: "LINHA DO TEMPO",
            items: [
              { year: "1989", caption: "INÍCIO", icon: "spark" },
              { year: "1991", caption: "PÚBLICO", icon: "code" },
              { year: "HOJE", caption: "PSF", icon: "community" },
            ],
          },
        },
        {
          id: "python-name-story",
          phase: "PARTE 1 · CONHEÇA O PYTHON",
          type: "lesson",
          title: "Por que o nome Python?",
          body: [
            "Quando escolheu o nome, Guido estava lendo roteiros de Monty Python's Flying Circus.",
            "A referência veio do programa de comédia: o nome Python não foi escolhido por causa da cobra.",
          ],
          note: "Essa é a origem documentada do nome; não precisamos inventar uma história mais dramática.",
          mompy: "Identidade resolvida: Guido iniciou o projeto, o anúncio público veio em 1991 e o nome nasceu dos roteiros de Monty Python.",
          mompyVisible: true,
          aux: {
            kind: "video",
            src: "./assets/classroom/monty-python-origin-clip-v1.mp4?v=1",
            alt: "Trecho de Monty Python's Flying Circus",
          },
        },
        {
          id: "history-check",
          phase: "INVESTIGAÇÃO 1 · REVISÃO",
          type: "choice",
          title: "Quem criou Python?",
          body: ["Identifique a pessoa que iniciou o desenvolvimento da linguagem."],
          choices: [
            { text: "Guido van Rossum", correct: true },
            { text: "Monty Python", correct: false },
            { text: "Uma empresa de computadores", correct: false },
          ],
          success: "Correto. Guido van Rossum iniciou Python em dezembro de 1989.",
          error: "Ainda não. A pergunta pede o nome da pessoa apresentada no arquivo de origem.",
          hint: "Observe o nome exibido ao lado do retrato na telinha.",
          mompyVisible: false,
          keepAuxDuringQuestion: true,
          aux: { kind: "fact", label: "CRIADOR DO PYTHON", icon: "?", title: "QUEM FOI?", subtitle: "IDENTIFIQUE A PESSOA" },
          auxSuccess: { kind: "fact", label: "CRIADOR DO PYTHON", icon: "G", title: "GUIDO VAN ROSSUM", subtitle: "INICIOU O PROJETO EM 1989" },
        },
        {
          id: "name-origin",
          phase: "INVESTIGAÇÃO 2 · REVISÃO",
          type: "choice",
          title: "De onde veio o nome Python?",
          body: ["Escolha a origem correta do nome da linguagem."],
          choices: [
            { text: "De uma espécie de cobra", correct: false },
            { text: "Do programa de comédia Monty Python", correct: true },
            { text: "De uma sigla de computador", correct: false },
          ],
          success: "Isso mesmo: o nome veio da comédia, não da cobra.",
          error: "Ainda não. O nome não descreve um animal nem é uma sigla técnica.",
          hint: "Guido era fã de um programa britânico de comédia.",
          mompyVisible: false,
          keepAuxDuringQuestion: true,
          aux: { kind: "fact", label: "ORIGEM DO NOME", icon: "?", title: "INVESTIGUE", subtitle: "ESCOLHA UMA RESPOSTA" },
          auxSuccess: { kind: "fact", label: "ORIGEM DO NOME", icon: "TV", title: "MONTY PYTHON", subtitle: "PROGRAMA BRITÂNICO DE COMÉDIA" },
        },
        {
          id: "python-purpose-check",
          phase: "INVESTIGAÇÃO 3 · REVISÃO",
          type: "choice",
          title: "O que fazemos com Python?",
          body: ["Escolha a opção que melhor resume o conceito apresentado no começo da aula."],
          choices: [
            { text: "Damos ao computador liberdade para adivinhar o que queremos", correct: false },
            { text: "Usamos apenas para desenhar cobras na tela", correct: false },
            { text: "Escrevemos instruções que o computador pode executar", correct: true },
          ],
          success: "Perfeito. Programar em Python é escrever instruções claras que o computador pode executar.",
          error: "Ainda não. Volte à ideia central apresentada no começo: o computador precisa receber instruções claras.",
          hint: "Pense no caminho mostrado na telinha: ideia → código → execução.",
          mompyVisible: false,
          keepAuxDuringQuestion: true,
          aux: { kind: "fact", label: "IDEIA CENTRAL", icon: "?", title: "PARA QUE SERVE?", subtitle: "RECORDE A PRIMEIRA EXPLICAÇÃO" },
          auxSuccess: { kind: "fact", label: "IDEIA CENTRAL", icon: "→", title: "IDEIA → CÓDIGO", subtitle: "INSTRUÇÕES PARA O COMPUTADOR" },
        },
        {
          id: "uses",
          phase: "PARTE 1 · CONHEÇA O PYTHON",
          type: "cards",
          title: "Uma linguagem, muitos usos",
          body: [
            "Escolha uma área. A telinha do Mompy vai mostrar uma prévia visual de código e transformar cada sequência em uma cena.",
            "Isto é uma demonstração de possibilidades, não um exercício nem um programa para copiar. Cada comando será apresentado somente quando chegar o momento certo na trilha.",
          ],
          cards: [
            {
              label: "AUTOMAÇÃO",
              detail: "um programa repete tarefas com precisão",
              demoKind: "automation-sync",
              code: "for _ in range(3):\n    braco.ir_ate(bloco)\n    braco.pegar()\n    braco.levantar()\n    braco.mover()\n    braco.soltar()",
              result: "3 TAREFAS CONCLUÍDAS",
              resultCaption: "A ROTINA FOI AUTOMATIZADA",
              running: "Python executando uma rotina automática",
              image: "./assets/classroom/use-case-automation-v1.png?v=2",
              imageAlt: "Braço robótico organizando caixas em uma esteira",
            },
            {
              label: "SITES",
              detail: "um servidor Python entrega páginas na internet",
              demoKind: "sites-delivery",
              codeScroll: true,
              code: "from http.server import (\n    test,\n)\nHost = \"localhost\"\nPorta = 8000\nProto = \"HTTP/1.0\"\nUrl = \"http://localhost\"\nprint(\"SERVIDOR PRONTO\")\nprint(Url)\ntry:\n    test(\n        port=Porta,\n        bind=Host,\n        protocol=Proto,\n    )\nexcept KeyboardInterrupt:\n    print(\"ENCERRANDO\")\nfinally:\n    print(\n        \"SERVIDOR FECHADO\"\n    )",
              result: "SITE DISPONÍVEL",
              resultCaption: "O SERVIDOR ENTREGOU A PÁGINA",
              running: "Python iniciando um servidor de páginas",
              image: "./assets/classroom/use-case-web-v1.png?v=2",
              imageAlt: "Página de site conectada a um servidor e a um celular",
            },
            {
              label: "DADOS E IA",
              detail: "dados viram medidas, padrões e previsões",
              demoKind: "data-ai-sequence",
              codeScroll: true,
              code: "dados = [\n    12,\n    18,\n    15,\n    21,\n]\nquantidade = len(dados)\ntotal = sum(dados)\nmedia = total / quantidade\nmenor = min(dados)\nmaior = max(dados)\namplitude = maior - menor\nprint(\n    \"MÉDIA\",\n    media,\n)\nprint(\n    \"AMPLITUDE\",\n    amplitude,\n)",
              result: "MÉDIA: 16.5",
              resultCaption: "OS DADOS REVELARAM UM PADRÃO",
              running: "Python analisando os dados",
              image: "./assets/classroom/use-case-data-ai-v1.png?v=2",
              imageAlt: "Dados conectados a um módulo inteligente e a um gráfico crescente",
            },
            {
              label: "CIÊNCIA E EDUCAÇÃO",
              detail: "pesquisas, simulações e aprendizado ganham ferramentas",
              demoKind: "science-education-sequence",
              codeScroll: true,
              code: "medidas = [\n    20.1,\n    20.4,\n    20.8,\n]\ninicio = medidas[0]\nfim = medidas[-1]\nvariacao = fim - inicio\namostras = len(medidas)\ntotal = sum(medidas)\nmedia = total / amostras\nprint(\n    \"MÉDIA\",\n    f\"{media:.1f}\",\n)\nprint(\n    \"VARIAÇÃO\",\n    f\"{variacao:.1f}\",\n)\nprint(\n    \"UNIDADE: CELSIUS\"\n)",
              result: "VARIAÇÃO: 0.7 °C",
              resultCaption: "A MEDIÇÃO VIROU CONHECIMENTO",
              running: "Python calculando uma observação científica",
              image: "./assets/classroom/use-case-science-v1.png?v=2",
              imageAlt: "Microscópio, folha, livro e molécula em um laboratório",
            },
          ],
          mompy: "Esta prévia mostrou código virando ação. Agora vamos olhar para a etapa central desse caminho: o intérprete que lê o código.",
          mompyVisible: true,
          actionLabel: "CONTINUAR",
        },
        {
          id: "instruction",
          phase: "PARTE 2 · COMO UM PROGRAMA FUNCIONA",
          type: "lesson",
          title: "Da ideia humana à ação da máquina",
          lead: "O computador não adivinha: ele precisa de uma instrução completa.",
          body: [
            "Código é o texto escrito em Python. Executar é pedir que esse código seja lido e que suas instruções sejam realizadas.",
            "A resposta produzida durante a execução é chamada de saída ou resultado.",
          ],
          bullets: ["código: o que foi escrito", "execução: Python realiza a instrução", "resultado: a resposta produzida"],
          definition: "Instrução é um passo escrito que especifica uma ação para o computador executar.",
          mentalModel: "CÓDIGO → EXECUÇÃO → RESULTADO",
          mompy: "Esses três momentos não são sinônimos. Primeiro existe código; depois existe execução; só então pode existir resultado.",
          mompyVisible: true,
        },
        {
          id: "interpreter",
          phase: "PARTE 2 · QUEM LÊ O CÓDIGO",
          type: "lesson",
          title: "Existe um intérprete entre você e a máquina",
          lead: "Python é uma linguagem interpretada.",
          body: [
            "Isso significa que um intérprete lê o código Python e conduz a execução das instruções.",
            "Quando dizemos que 'Python executa o código', estamos resumindo o caminho entre o código recebido, a ação realizada e a saída produzida.",
          ],
          definition: "Intérprete é o programa responsável por ler e executar código escrito em uma linguagem como Python.",
          mentalModel: "Você escreve para o intérprete; o intérprete transforma essas instruções em trabalho real da máquina.",
          warning: "Se ele encontrar uma instrução incompleta ou escrita fora das regras, interrompe aquela execução e informa um erro em vez de adivinhar.",
          mompy: "Observe o meio do caminho: o código entra, o intérprete conduz a execução e a saída aparece depois.",
          mompyVisible: true,
          aux: { kind: "interpreter-sequence", alt: "O intérprete Python recebe instruções, processa o código e comanda a máquina" },
        },
        {
          id: "code-flow",
          phase: "PARTE 2 · O CAMINHO DO PROGRAMA",
          type: "lesson",
          title: "Três momentos diferentes",
          body: [
            "Quando você escreve, ainda existe apenas código. Durante a execução, o intérprete lê a instrução. O que a ação produz aparece como resultado.",
            "Esses momentos formam uma sequência: código, execução e resultado.",
          ],
          processStages: [
            { label: "CÓDIGO", detail: "a instrução escrita" },
            { label: "EXECUÇÃO", detail: "o intérprete realiza a ação" },
            { label: "RESULTADO", detail: "a resposta produzida" },
          ],
          mompy: "Para o intérprete reconhecer uma instrução, a escrita precisa seguir regras. Esse é o próximo conceito: sintaxe.",
          mompyVisible: true,
        },
        {
          id: "syntax-intro",
          phase: "PARTE 2 · AS REGRAS DA ESCRITA",
          type: "lesson",
          title: "Sintaxe organiza a escrita do código",
          body: [
            "Toda linguagem possui regras de escrita. Em programação, esse conjunto de regras recebe o nome de sintaxe.",
            "Em Python, a indentação — os espaços no início da linha — delimita quais instruções pertencem a um bloco, em vez de chaves.",
            "O símbolo # marca um comentário. Ele permite registrar uma observação no código.",
            "Aqui, bloco é o trecho delimitado pela indentação; por exemplo, # revisar mensagem é uma observação marcada como comentário.",
          ],
          definition: "Sintaxe é o conjunto de regras que determina como o código precisa ser escrito para que o intérprete consiga entendê-lo.",
          mentalModel: "Pense na sintaxe como a organização visível do código: palavras, símbolos e posição comunicam estrutura ao intérprete.",
          note: "Nesta aula, basta reconhecer que comentários usam # e que a indentação delimita blocos. As próximas Partes aplicam regras de sintaxe a texto e a uma chamada completa.",
          mompy: "Já sabemos que a escrita tem regras. Agora vamos identificar exatamente onde um texto começa e termina.",
          mompyVisible: true,
          aux: {
            kind: "syntax-animation",
            code: 'print("Olá, Mompy!")',
            functionLabel: "PALAVRA",
            stringLabel: "CONTEÚDO",
            parenthesesLabel: "SÍMBOLOS",
            validLabel: "SINTAXE VÁLIDA",
            waitingLabel: "Cursor aguardando",
            alt: "Uma prévia de instrução sendo digitada e validada pela sintaxe Python",
          },
        },
        {
          id: "text-intro",
          phase: "PARTE 3 · A INFORMAÇÃO QUE SERÁ MOSTRADA",
          type: "lesson",
          title: "Texto é um valor — e as aspas o identificam",
          body: [
            "Uma informação textual, como Olá, Mompy!, é chamada de string em Python. String significa uma sequência de caracteres: letras, espaços, números ou sinais tratados como texto.",
            "As aspas marcam exatamente onde essa string começa e termina. O conteúdo é Olá, Mompy!; as aspas são parte da escrita do código e não aparecem no resultado.",
            "Por exemplo, \"123\" continua sendo uma string: dentro das aspas, os três caracteres são tratados como texto.",
          ],
          definition: "String é um valor de texto delimitado por aspas, como \"Olá, Mompy!\".",
          mentalModel: "As aspas funcionam como uma embalagem: dizem ao intérprete que tudo dentro delas deve ser tratado como texto.",
          mompy: "Agora já temos a informação que queremos mostrar. Falta conhecer a ação que a colocará na saída.",
          mompyVisible: true,
          aux: {
            kind: "string-value-animation",
            text: "Olá, Mompy!",
            kicker: "VALOR DE TEXTO",
            explanation: "AS ASPAS DELIMITAM A STRING",
            alt: "O texto Olá, Mompy sendo digitado e delimitado por duas aspas",
          },
        },
        {
          id: "print-purpose",
          phase: "PARTE 3 · PRIMEIRO, O QUE É UMA FUNÇÃO",
          type: "lesson",
          title: "Uma função é uma ação pronta",
          lead: "Antes de conhecer print, precisamos entender a ideia de função.",
          body: [
            "Função é uma ação já definida que pode ser chamada pelo nome. Chamar a função é pedir que essa ação seja realizada.",
            "A função pronta que usaremos chama-se print. O nome print identifica a ação de exibir informação na saída.",
            "Em print(\"Olá, Mompy!\"), print é o nome da ação e o texto entre aspas é a informação entregue à função.",
            "Sua assinatura completa é print(*objects, sep=' ', end='\\n', file=sys.stdout, flush=False).",
            "As informações passadas sem nome são convertidas em texto, separadas por sep e seguidas por end. Sem informação, print() escreve somente end.",
            "file indica o destino e precisa oferecer write(string); quando omitido, usa sys.stdout.",
          ],
          definition: "Função é uma ação já definida que pode ser chamada pelo nome.",
          mentalModel: "O nome identifica a ação; os parênteses formam a chamada e recebem as informações entregues à função.",
          note: "O nome print segue uma convenção antiga da computação, já presente em linguagens como BASIC e Fortran. Não existe uma origem oficial dramática para esse nome.",
          warning: "Assinatura é a forma de referência que mostra o nome da função e as opções que ela aceita. A assinatura completa fica registrada aqui, mas nesta aula você só precisa compreender o nome print, os parênteses da chamada e a informação colocada dentro deles.",
          mompy: "Primeiro veio a ideia de função; agora ela tem um nome: print. Veja a chamada produzir uma saída sem configuração extra.",
          mompyVisible: true,
          aux: {
            kind: "print-function-animation",
            code: 'print("Olá, Mompy!")',
            output: "Olá, Mompy!",
            kicker: "FUNÇÃO — PRINT",
            resultLabel: "A INFORMAÇÃO FICOU VISÍVEL",
            alt: "A função print sendo digitada e executada para tornar uma informação visível",
          },
        },
        {
          id: "first-print",
          phase: "PRÁTICA GUIADA · SUA PRIMEIRA INSTRUÇÃO",
          type: "run",
          title: "Acompanhe um programa nascer",
          body: [
            "Nosso objetivo é fazer aparecer a mensagem Olá, Mompy!.",
            "Você já conhece a função, o texto e o caminho da execução. Agora controlará três momentos: revelar o código, pedir a execução ao intérprete e observar somente depois o resultado.",
          ],
          code: "print(\"Olá, Mompy!\")",
          output: "Olá, Mompy!",
          guidedExecution: true,
          hideCodeUntilReveal: true,
          inputLabel: "CÓDIGO",
          outputLabel: "RESULTADO",
          processStages: [
            { label: "CÓDIGO", detail: "revele a instrução" },
            { label: "EXECUÇÃO", detail: "entregue ao intérprete" },
            { label: "RESULTADO", detail: "observe a resposta" },
          ],
          note: "A PEP 20 resume uma ideia que aparece aqui: “Simple is better than complex”. Uma chamada curta já consegue tornar uma mensagem visível.",
          mompy: "Revele o código, entregue-o ao intérprete e compare a instrução com a saída. Depois veremos o que muda quando existem duas linhas.",
          mompyVisible: true,
        },
        {
          id: "predict-output",
          phase: "PREVEJA ANTES DE EXECUTAR",
          type: "choice",
          title: "O que aparecerá?",
          code: "print(\"Python é incrível!\")",
          choices: [
            { text: "print(\"Python é incrível!\")", correct: false, code: true },
            { text: "Python é incrível!", correct: true, code: true },
            { text: "\"Python é incrível!\"", correct: false, code: true },
          ],
          success: "Perfeito. A saída mostra a mensagem; print e as aspas continuam no código.",
          error: "Compare o código com o resultado anterior: o que a tela mostrou?",
          hint: "A saída contém a mensagem, sem a palavra print e sem as aspas.",
          mompyVisible: false,
          keepAuxDuringQuestion: true,
          aux: { label: "RESULTADO", value: "?" },
          auxSuccess: { label: "RESULTADO", value: "Python é incrível!" },
        },
        {
          id: "two-lines-demo",
          phase: "PARTE 4 · ORDEM DE EXECUÇÃO",
          type: "lesson",
          title: "Python lê de cima para baixo",
          body: [
            "Quando um programa possui mais de uma instrução, Python executa a primeira linha até o fim e só então passa para a próxima.",
            "Por isso, a saída aparece na mesma ordem das instruções no código.",
          ],
          code: "print(\"Linha 1\")\nprint(\"Linha 2\")",
          note: "A ordem da saída acompanha a ordem das instruções: primeiro Linha 1; depois Linha 2.",
          mompy: "Trace uma linha de cada vez: conclua a primeira e avance para a segunda. Depois desmontaremos a chamada completa símbolo por símbolo.",
          mompyVisible: true,
          aux: {
            kind: "line-order-animation",
            kicker: "ORDEM DE EXECUÇÃO",
            codeLabel: "CÓDIGO",
            outputLabel: "RESULTADO",
            codeLines: ['print("Linha 1")', 'print("Linha 2")'],
            outputLines: ["Linha 1", "Linha 2"],
            footer: "↓ PYTHON LÊ DE CIMA PARA BAIXO",
            alt: "As duas instruções print sendo executadas de cima para baixo",
          },
        },
        {
          id: "two-lines",
          phase: "ORDEM DE EXECUÇÃO",
          type: "choice",
          title: "Duas instruções, duas linhas",
          body: ["Python executa as instruções de cima para baixo."],
          code: "print(\"Primeiro\")\nprint(\"Depois\")",
          choices: [
            { text: "Primeiro\nDepois", correct: true, code: true },
            { text: "Depois\nPrimeiro", correct: false, code: true },
            { text: "Primeiro Depois", correct: false, code: true },
          ],
          success: "Certo. Cada print produz uma linha, seguindo a ordem do código.",
          error: "Observe qual instrução está na primeira linha do código.",
          hint: "Leia de cima para baixo; cada print termina sua própria linha.",
          mompyVisible: false,
          aux: { label: "RESULTADO", value: "?" },
          auxSuccess: { label: "RESULTADO", value: "Primeiro\nDepois" },
        },
        {
          id: "print-anatomy",
          phase: "PARTE 5 · MONTE A CHAMADA COMPLETA",
          type: "inspect",
          title: "Leia print sem pular nenhum símbolo",
          body: ["Agora que você viu a função em execução e acompanhou duas linhas, abra cada peça da chamada completa."],
          code: "print(\"Olá, Mompy!\")",
          inspectItems: [
            { label: "print", detail: "o nome da função pronta que exibe informação" },
            { label: "( )", detail: "abrem e fecham a chamada da função" },
            { label: "\" \"", detail: "abrem e fecham a string dentro da chamada" },
            { label: "Olá, Mompy!", detail: "o conteúdo da string que aparecerá na saída" },
          ],
          mompy: "São dois pares independentes: os parênteses delimitam a chamada; as aspas delimitam o texto dentro dela.",
          mompyVisible: true,
          aux: {
            kind: "reading-animation",
            action: "print",
            text: '("Olá, Mompy!")',
            displayText: '"Olá, Mompy!"',
            kicker: "LEITURA",
            actionLabel: "AÇÃO",
            textLabel: "TEXTO",
            executeLabel: "⚡ PRIMEIRO ENTENDE • DEPOIS EXECUTA",
            alt: "Leitura completa da função print, dos parênteses e da string entre aspas",
          },
          actionLabel: "CÓDIGO ENTENDIDO",
        },
        {
          id: "syntax-pairs",
          phase: "PARTE 5 · MONTE PRINT SEM LACUNAS",
          type: "lesson",
          title: "Aspas e parênteses trabalham em pares",
          body: [
            "Os parênteses abrem e fecham a chamada da função. Dentro deles, as aspas abrem e fecham o texto.",
            "São pares independentes: se qualquer um ficar aberto, a instrução fica incompleta e Python não consegue executá-la.",
          ],
          code: "print(\"Eu consegui!\")",
          bullets: ["print — nome da ação", "( ) — abrem e fecham a chamada", "\" \" — abrem e fecham o texto"],
          warning: "Confira sempre os dois pares antes de executar: uma aspa de abertura precisa de fechamento; um parêntese de abertura também.",
          mompy: "Cheque os dois pares separadamente. Quando chamada e texto estão fechados, a instrução está pronta para execução.",
          mompyVisible: true,
          aux: {
            kind: "pair-animation",
            code: 'print("Eu consegui!")',
            kicker: "PARES DA SINTAXE",
            parenthesesLabel: "PARÊNTESES: CHAMADA COMPLETA",
            quotesLabel: "ASPAS: TEXTO COMPLETO",
            validLabel: "✓ FORMA COMPLETA",
            alt: "Parênteses e aspas completando a instrução print em pares",
          },
        },
        {
          id: "fill-text",
          phase: "COMPLETE A INSTRUÇÃO",
          type: "choice",
          title: "Faça aparecer: Eu consegui!",
          code: "print(__________)",
          choices: [
            { text: "Eu consegui!", correct: false, code: true },
            { text: "print", correct: false, code: true },
            { text: "\"Eu consegui!\"", correct: true, code: true },
          ],
          success: "Isso. As aspas dizem a Python que Eu consegui! é um texto.",
          error: "A lacuna precisa receber um texto completo.",
          hint: "Textos começam e terminam com aspas.",
          mompyVisible: false,
          keepAuxDuringQuestion: true,
          aux: { label: "RESULTADO", value: "?" },
          auxSuccess: { label: "RESULTADO", value: "Eu consegui!" },
        },
        {
          id: "mastery-python",
          phase: "VERIFICAÇÃO FINAL · 1/5",
          type: "choice",
          title: "Qual frase descreve Python?",
          choices: [
            { text: "Um componente físico do computador", correct: false },
            { text: "Uma linguagem para escrever instruções", correct: true },
            { text: "Somente um programa de desenho", correct: false },
          ],
          success: "Correto.",
          error: "Python não é uma peça física nem serve para apenas uma tarefa.",
          hint: "Pense na forma usada para conversar com o computador por instruções.",
          mompyVisible: false,
        },
        {
          id: "mastery-print",
          phase: "VERIFICAÇÃO FINAL · 2/5",
          type: "choice",
          title: "O que print faz?",
          choices: [
            { text: "Mostra todas as palavras que existem no código", correct: false },
            { text: "Transforma todo texto em número", correct: false },
            { text: "Exibe uma informação como saída", correct: true },
          ],
          success: "Correto.",
          error: "Lembre da primeira resposta da máquina.",
          hint: "Usamos print quando queremos ver uma mensagem ou resultado.",
          mompyVisible: false,
        },
        {
          id: "mastery-text",
          phase: "VERIFICAÇÃO FINAL · 3/5",
          type: "choice",
          title: "Em print(\"Oi\"), qual parte é o texto?",
          choices: [
            { text: "print", correct: false, code: true },
            { text: "\"Oi\"", correct: true, code: true },
            { text: "( )", correct: false, code: true },
          ],
          success: "Correto.",
          error: "Procure o conteúdo delimitado pelas aspas.",
          hint: "As aspas cercam o texto.",
          mompyVisible: false,
        },
        {
          id: "mastery-order",
          phase: "VERIFICAÇÃO FINAL · 4/5",
          type: "choice",
          title: "Qual será a saída?",
          code: "print(\"A\")\nprint(\"B\")",
          choices: [
            { text: "A\nB", correct: true, code: true },
            { text: "B\nA", correct: false, code: true },
            { text: "AB", correct: false, code: true },
          ],
          success: "Correto.",
          error: "Leia uma instrução por vez, de cima para baixo.",
          hint: "Cada print cria uma linha de saída.",
          mompyVisible: false,
        },
        {
          id: "mastery-syntax",
          phase: "VERIFICAÇÃO FINAL · 5/5",
          type: "choice",
          title: "Qual código está completo?",
          choices: [
            { text: "print(\"Pronto)", correct: false, code: true },
            { text: "print\"Pronto\"", correct: false, code: true },
            { text: "print(\"Pronto\")", correct: true, code: true },
          ],
          success: "Verificação concluída.",
          error: "Confira os dois pares: aspas e parênteses.",
          hint: "A forma completa é: ação, abre parêntese, texto entre aspas e fecha parêntese.",
          mompyVisible: false,
        },
        {
          id: "summary",
          phase: "AULA CONCLUÍDA",
          type: "summary",
          title: "Você já consegue fazer Python responder",
          learned: [
            "Python é uma linguagem de programação",
            "o intérprete lê e executa o código",
            "sintaxe organiza a escrita válida",
            "uma função é uma ação pronta chamada pelo nome",
            "print é a função que exibe informações",
            "aspas delimitam strings",
            "instruções simples seguem uma ordem",
          ],
          missions: ["transmitir mensagens", "montar print corretamente", "prever saídas", "criar duas linhas"],
          mompy: "Você partiu da origem do Python, acompanhou o intérprete e chegou a uma chamada completa de print. Agora use as missões para provar que cada símbolo e cada linha têm um propósito.",
          mompyVisible: true,
          actionLabel: "IR PARA AS MISSÕES",
        },
      ],
    },
    "en-US": {
      title: "Lesson 1 — Meet Python",
      subtitle: "Meet Python and give your first instruction",
      estimatedMinutes: 20,
      steps: [
        { id: "opening", phase: "LESSON 1", type: "lesson", title: "Meet Python and give your first instruction", body: ["Today you will learn what Python is and make a machine answer for the first time."], bullets: ["discover what Python is", "learn where it came from", "show your first message"], mompy: "We are starting from zero. You do not need any programming experience.", mompyVisible: true, actionLabel: "START", actionOnMompy: true },
        { id: "what-is-python", phase: "PART 1 · MEET PYTHON", type: "lesson", title: "What is Python?", lead: "Python is a programming language.", body: ["It lets us write instructions that a computer can execute.", "A programming language provides names and rules that turn a human idea into exact steps. Those written steps form code.", "In this lesson, you will follow that path from Python's origin to one complete instruction.", "Conceptual example: ‘display a message’ is the idea; code will be the precise instruction that the computer can execute."], definition: "A programming language is a set of names and rules used to write instructions that a computer can execute.", mentalModel: "HUMAN IDEA → EXACT STEPS → CODE", note: "You do not need to memorize code yet. First we will understand Python's identity; then we will see who reads instructions and which rules organize their writing.", mompy: "Programming means explaining precisely what the machine should do.", mompyVisible: true, aux: { kind: "idea-code", idea: "IDEA", arrow: "→", code: "CODE", subtitle: "EXACT STEPS FOR THE MACHINE", steps: ["RECEIVE A HUMAN IDEA", "BREAK IT INTO LOGICAL STEPS", "WRITE PRECISE INSTRUCTIONS", "RUN WITHOUT AMBIGUITY"], duration: 24000, alt: "A human idea being transformed into code step by step" } },
        { id: "guido", phase: "PART 1 · MEET PYTHON", type: "lesson", title: "Who started it?", body: ["Guido van Rossum started Python in December 1989 as a personal project during a week around Christmas.", "He wanted to create a successor to the ABC language that would also appeal to people familiar with Unix and C."], definition: "Successor, in this context, means a new language intended to continue an earlier path: Python was conceived as a successor to ABC.", mompy: "The origin had a concrete goal: start from what already existed and build a new language. Now let us mark when it became public.", mompyVisible: true, aux: { kind: "identity", label: "ORIGIN FILE", image: "./assets/classroom/guido-van-rossum-crt-v2.png?v=1", alt: "Green CRT pixel-art portrait of Guido van Rossum", title: "GUIDO VAN ROSSUM", subtitle: "CREATOR OF PYTHON", facts: ["DEC 1989", "ABC → PYTHON"] } },
        { id: "timeline", phase: "PART 1 · MEET PYTHON", type: "lesson", title: "A story that became public", body: ["After starting in December 1989, Guido announced Python publicly on Usenet in February 1991.", "Today, the Python Software Foundation, or PSF, holds the project's rights."], definition: "PSF stands for Python Software Foundation, the organization that currently holds the project's rights.", note: "The dates provide context; you do not need to memorize them.", mompy: "Keep the sequence, not the numbers: a personal project, a public announcement, and a foundation that holds the project's rights.", mompyVisible: true, aux: { kind: "timeline", label: "TIMELINE", items: [{ year: "1989", caption: "START", icon: "spark" }, { year: "1991", caption: "PUBLIC", icon: "code" }, { year: "TODAY", caption: "PSF", icon: "community" }] } },
        { id: "python-name-story", phase: "PART 1 · MEET PYTHON", type: "lesson", title: "Why the name Python?", body: ["When choosing the name, Guido was reading scripts from Monty Python's Flying Circus.", "The reference came from the comedy show: the name Python was not chosen because of the snake."], note: "That is the documented origin of the name; we do not need to invent a more dramatic story.", mompy: "Identity resolved: Guido started the project, the public announcement came in 1991, and the name came from Monty Python scripts.", mompyVisible: true, aux: { kind: "video", src: "./assets/classroom/monty-python-origin-clip-v1.mp4?v=1", alt: "Clip from Monty Python's Flying Circus" } },
        { id: "history-check", phase: "INVESTIGATION 1 · REVIEW", type: "choice", title: "Who created Python?", body: ["Identify the person who began developing the language."], choices: [{ text: "Guido van Rossum", correct: true }, { text: "Monty Python", correct: false }, { text: "A computer company", correct: false }], success: "Correct. Guido van Rossum started Python in December 1989.", error: "Not yet. The question asks for the person introduced in the origin file.", hint: "Look at the name shown beside the portrait on the small monitor.", mompyVisible: false, keepAuxDuringQuestion: true, aux: { kind: "fact", label: "PYTHON'S CREATOR", icon: "?", title: "WHO WAS IT?", subtitle: "IDENTIFY THE PERSON" }, auxSuccess: { kind: "fact", label: "PYTHON'S CREATOR", icon: "G", title: "GUIDO VAN ROSSUM", subtitle: "STARTED THE PROJECT IN 1989" } },
        { id: "name-origin", phase: "INVESTIGATION 2 · REVIEW", type: "choice", title: "Where did the name Python come from?", body: ["Choose the language name's real origin."], choices: [{ text: "A species of snake", correct: false }, { text: "The Monty Python comedy show", correct: true }, { text: "A computer acronym", correct: false }], success: "Exactly: the name came from comedy, not the snake.", error: "Not yet. The name does not describe an animal and is not a technical acronym.", hint: "Remember the culture archive shown before this question.", mompyVisible: false, keepAuxDuringQuestion: true, aux: { kind: "fact", label: "NAME ORIGIN", icon: "?", title: "INVESTIGATE", subtitle: "CHOOSE AN ANSWER" }, auxSuccess: { kind: "fact", label: "NAME ORIGIN", icon: "TV", title: "MONTY PYTHON", subtitle: "BRITISH COMEDY SHOW" } },
        { id: "python-purpose-check", phase: "INVESTIGATION 3 · REVIEW", type: "choice", title: "What do we use Python for?", body: ["Choose the option that best summarizes the concept presented at the beginning of the lesson."], choices: [{ text: "We let the computer guess what we want", correct: false }, { text: "We use it only to draw snakes on the screen", correct: false }, { text: "We write instructions that the computer can execute", correct: true }], success: "Perfect. Programming in Python means writing clear instructions that the computer can execute.", error: "Not yet. Return to the central idea from the beginning: the computer needs clear instructions.", hint: "Remember the path shown on the small monitor: idea → code → execution.", mompyVisible: false, keepAuxDuringQuestion: true, aux: { kind: "fact", label: "CENTRAL IDEA", icon: "?", title: "WHAT IS IT FOR?", subtitle: "RECALL THE FIRST EXPLANATION" }, auxSuccess: { kind: "fact", label: "CENTRAL IDEA", icon: "→", title: "IDEA → CODE", subtitle: "INSTRUCTIONS FOR THE COMPUTER" } },
        {
          id: "uses",
          phase: "PART 1 · MEET PYTHON",
          type: "cards",
          title: "One language, many uses",
          body: ["Choose an area. Mompy's small monitor will show a visual preview of code and turn each sequence into a scene.", "This is a demonstration of possibilities, not an exercise or a program to copy. Each command will be introduced only when its proper moment arrives in the learning path."],
          cards: [
            { label: "AUTOMATION", detail: "a program repeats tasks precisely", demoKind: "automation-sync", code: "for _ in range(3):\n    braco.ir_ate(bloco)\n    braco.pegar()\n    braco.levantar()\n    braco.mover()\n    braco.soltar()", result: "3 TASKS COMPLETED", resultCaption: "THE ROUTINE WAS AUTOMATED", running: "Python running an automated routine", image: "./assets/classroom/use-case-automation-v1.png?v=2", imageAlt: "A robotic arm sorting boxes on a conveyor" },
            { label: "WEBSITES", detail: "a Python server delivers pages online", demoKind: "sites-delivery", codeScroll: true, code: "from http.server import (\n    test,\n)\nHost = \"localhost\"\nPort = 8000\nProtocol = \"HTTP/1.0\"\nUrl = \"http://localhost\"\nprint(\"SERVER READY\")\nprint(Url)\ntry:\n    test(\n        port=Port,\n        bind=Host,\n        protocol=Protocol,\n    )\nexcept KeyboardInterrupt:\n    print(\"STOPPING\")\nfinally:\n    print(\"SERVER CLOSED\")", result: "SITE AVAILABLE", resultCaption: "THE SERVER DELIVERED THE PAGE", running: "Python starting a web server", image: "./assets/classroom/use-case-web-v1.png?v=2", imageAlt: "A web page connected to a server and a phone" },
            { label: "DATA AND AI", detail: "data becomes measurements, patterns, and predictions", demoKind: "data-ai-sequence", codeScroll: true, code: "data = [\n    12,\n    18,\n    15,\n    21,\n]\ncount = len(data)\ntotal = sum(data)\naverage = total / count\nminimum = min(data)\nmaximum = max(data)\nspread = maximum - minimum\nprint(\n    \"AVERAGE\",\n    average,\n)\nprint(\n    \"SPREAD\",\n    spread,\n)", result: "AVERAGE: 16.5", resultCaption: "THE DATA REVEALED A PATTERN", running: "Python analyzing data", image: "./assets/classroom/use-case-data-ai-v1.png?v=2", imageAlt: "Data connected to an intelligent module and a rising chart" },
            { label: "SCIENCE AND EDUCATION", detail: "research, simulations, and learning gain new tools", demoKind: "science-education-sequence", codeScroll: true, code: "readings = [\n    20.1,\n    20.4,\n    20.8,\n]\nstart = readings[0]\nend = readings[-1]\nchange = end - start\nsamples = len(readings)\ntotal = sum(readings)\naverage = total / samples\nprint(\n    \"AVERAGE\",\n    f\"{average:.1f}\",\n)\nprint(\n    \"CHANGE\",\n    f\"{change:.1f}\",\n)\nprint(\n    \"UNIT: CELSIUS\"\n)", result: "CHANGE: 0.7 °C", resultCaption: "A MEASUREMENT BECAME KNOWLEDGE", running: "Python calculating a scientific observation", image: "./assets/classroom/use-case-science-v1.png?v=2", imageAlt: "A microscope, leaf, book, and molecule in a laboratory" },
          ],
          mompy: "This preview showed code becoming action. Now we will look at the central step in that path: the interpreter that reads the code.",
          mompyVisible: true,
          actionLabel: "CONTINUE",
        },
        { id: "instruction", phase: "PART 2 · HOW A PROGRAM WORKS", type: "lesson", title: "From a human idea to a machine action", lead: "The computer does not guess: it needs a complete instruction.", body: ["Code is text written in Python. Running means asking for that code to be read and for its instructions to be carried out.", "The response produced during execution is called output or result."], bullets: ["code: what was written", "execution: Python performs the instruction", "output: the answer produced"], definition: "An instruction is a written step that specifies an action for the computer to execute.", mentalModel: "CODE → EXECUTION → OUTPUT", mompy: "Code is what you write. Execution is Python carrying it out. Output is what the program produces.", mompyVisible: true },
        { id: "interpreter", phase: "PART 2 · WHO READS THE CODE", type: "lesson", title: "An interpreter stands between you and the machine", lead: "Python is an interpreted language.", body: ["This means that an interpreter reads Python code and conducts the execution of its instructions.", "When we say that 'Python runs the code,' we are summarizing the path between received code, performed action, and produced output."], definition: "An interpreter is the program responsible for reading and executing code written in a language such as Python.", mentalModel: "You write for the interpreter; the interpreter turns those instructions into real work by the machine.", warning: "If it finds an incomplete instruction or one written outside the rules, it stops that execution and reports an error instead of guessing.", mompy: "Watch the middle of the path: code enters, the interpreter conducts execution, and output appears afterward.", mompyVisible: true, aux: { kind: "interpreter-sequence", alt: "The Python interpreter receives instructions, processes code, and controls the machine" } },
        { id: "code-flow", phase: "PART 2 · THE PROGRAM PATH", type: "lesson", title: "Three different moments", body: ["When you write, there is only code. During execution, the interpreter reads the instruction. What the action produces appears as output.", "Those moments form a sequence: code, execution, and output."], processStages: [{ label: "CODE", detail: "the written instruction" }, { label: "EXECUTION", detail: "the interpreter performs the action" }, { label: "OUTPUT", detail: "the answer produced" }], mompy: "For the interpreter to recognize an instruction, its writing must follow rules. That is the next concept: syntax.", mompyVisible: true },
        { id: "syntax-intro", phase: "PART 2 · WRITING RULES", type: "lesson", title: "Syntax organizes how code is written", body: ["Every language has writing rules. In programming, this set of rules is called syntax.", "In Python, indentation—the spaces at the beginning of a line—delimits which instructions belong to a block instead of braces.", "The # symbol marks a comment. It lets you record a note in the code.", "Here, a block is the section delimited by indentation; for example, # review message is a note marked as a comment."], definition: "Syntax is the set of rules that determines how code must be written so the interpreter can understand it.", mentalModel: "Think of syntax as the visible organization of code: words, symbols, and position communicate structure to the interpreter.", note: "In this lesson, it is enough to recognize that comments use # and indentation delimits blocks. The next Parts apply syntax rules to text and to a complete call.", mompy: "Now we know that writing has rules. Next, we will identify exactly where a piece of text begins and ends.", mompyVisible: true, aux: { kind: "syntax-animation", code: 'print("Hello, Mompy!")', functionLabel: "WORD", stringLabel: "CONTENT", parenthesesLabel: "SYMBOLS", validLabel: "VALID SYNTAX", waitingLabel: "Cursor waiting", alt: "A preview of an instruction being typed and validated by Python syntax" } },
        { id: "text-intro", phase: "PART 3 · THE INFORMATION TO DISPLAY", type: "lesson", title: "Text is a value—and quotes identify it", body: ["A piece of text such as Hello, Mompy! is called a string in Python. A string is a sequence of characters: letters, spaces, numbers, or signs treated as text.", "Quotes mark exactly where that string begins and ends. The content is Hello, Mompy!; the quotes belong to the code and do not appear in output.", "For example, \"123\" is still a string: inside quotes, all three characters are treated as text."], definition: "A string is a text value delimited by quotes, such as \"Hello, Mompy!\".", mentalModel: "Quotes work like packaging: they tell the interpreter that everything inside must be treated as text.", mompy: "We have the message. Next, we need to tell Python to show it.", mompyVisible: true, aux: { kind: "string-value-animation", text: "Hello, Mompy!", kicker: "TEXT VALUE", explanation: "QUOTES DELIMIT THE STRING", alt: "The text Hello, Mompy being typed and delimited by two quotation marks" } },
        { id: "print-purpose", phase: "PART 3 · FIRST, WHAT IS A FUNCTION", type: "lesson", title: "A function is a ready-made action", lead: "Before meeting print, we need to understand the idea of a function.", body: ["A function is an action already defined that can be called by name. Calling the function means asking for that action to be performed.", "The ready-made function we will use is called print. The name print identifies the action of displaying information as output.", "In print(\"Hello, Mompy!\"), print is the action's name and the quoted text is the information given to the function.", "Its complete signature is print(*objects, sep=' ', end='\\n', file=sys.stdout, flush=False).", "Information passed without a name is converted to text, separated by sep, and followed by end. With no information, print() writes only end.", "file selects the destination and must provide write(string); when omitted, it uses sys.stdout."], definition: "A function is an action already defined that can be called by name.", mentalModel: "The name identifies the action; parentheses form the call and receive the information given to the function.", note: "The name print follows an old computing convention already present in languages such as BASIC and Fortran. There is no official dramatic origin story for the name.", warning: "A signature is the reference form that shows a function's name and the options it accepts. The complete signature is recorded here, but in this lesson you only need to understand the name print, the call's parentheses, and the information placed inside them.", mompy: "First came the idea of a function; now it has a name: print. Watch the call produce output without extra setup.", mompyVisible: true, aux: { kind: "print-function-animation", code: 'print("Hello, Mompy!")', output: "Hello, Mompy!", kicker: "FUNCTION — PRINT", resultLabel: "THE INFORMATION BECAME VISIBLE", alt: "The print function being typed and executed to make information visible" } },
        { id: "first-print", phase: "GUIDED PRACTICE · YOUR FIRST INSTRUCTION", type: "run", title: "Watch a program come to life", body: ["Our goal is to display the message Hello, Mompy!.", "You already know the function, the text, and the execution path. Now you will control three moments: reveal the code, ask the interpreter to run it, and only then observe the output."], code: "print(\"Hello, Mompy!\")", output: "Hello, Mompy!", guidedExecution: true, hideCodeUntilReveal: true, inputLabel: "CODE", outputLabel: "OUTPUT", processStages: [{ label: "CODE", detail: "reveal the instruction" }, { label: "EXECUTION", detail: "give it to the interpreter" }, { label: "OUTPUT", detail: "observe the answer" }], note: "PEP 20 summarizes an idea visible here: “Simple is better than complex”. A short call can already make a message visible.", mompy: "Reveal the code, give it to the interpreter, and compare the instruction with the output. Next, we will see what changes when there are two lines.", mompyVisible: true },
        { id: "predict-output", phase: "PREDICT BEFORE RUNNING", type: "choice", title: "What will appear?", code: "print(\"Python is amazing!\")", choices: [{ text: "print(\"Python is amazing!\")", correct: false, code: true }, { text: "Python is amazing!", correct: true, code: true }, { text: "\"Python is amazing!\"", correct: false, code: true }], success: "Perfect. The output shows the message; print and the quotes stay in the code.", error: "Compare the code with the previous result: what did the monitor show?", hint: "Output contains the message without the word print or the quotes.", mompyVisible: false, keepAuxDuringQuestion: true, aux: { label: "OUTPUT", value: "?" }, auxSuccess: { label: "OUTPUT", value: "Python is amazing!" } },
        { id: "two-lines-demo", phase: "PART 4 · EXECUTION ORDER", type: "lesson", title: "Python reads from top to bottom", body: ["When a program has more than one instruction, Python executes the first line to completion and only then moves to the next.", "Therefore, output appears in the same order as the instructions in the code."], code: "print(\"Line 1\")\nprint(\"Line 2\")", note: "Output order follows instruction order: first Line 1; then Line 2.", mompy: "Trace one line at a time: finish the first and move to the second. Next, we will take the complete call apart symbol by symbol.", mompyVisible: true, aux: { kind: "line-order-animation", kicker: "EXECUTION ORDER", codeLabel: "CODE", outputLabel: "OUTPUT", codeLines: ['print("Line 1")', 'print("Line 2")'], outputLines: ["Line 1", "Line 2"], footer: "↓ PYTHON READS FROM TOP TO BOTTOM", alt: "Two print instructions executing from top to bottom" } },
        { id: "two-lines", phase: "EXECUTION ORDER", type: "choice", title: "Two instructions, two lines", body: ["Apply the top-to-bottom rule you just observed."], code: "print(\"First\")\nprint(\"Then\")", choices: [{ text: "First\nThen", correct: true, code: true }, { text: "Then\nFirst", correct: false, code: true }, { text: "First Then", correct: false, code: true }], success: "Correct. Each print creates a line in code order.", error: "Look at which instruction is on the first line.", hint: "Read from top to bottom; each print ends its own line.", mompyVisible: false },
        { id: "print-anatomy", phase: "PART 5 · BUILD THE COMPLETE CALL", type: "inspect", title: "Read print without skipping a symbol", body: ["Now that you have seen the function execute and followed two lines, open every piece of the complete call."], code: "print(\"Hello, Mompy!\")", inspectItems: [{ label: "print", detail: "the name of the ready-made function that displays information" }, { label: "( )", detail: "open and close the function call" }, { label: "\" \"", detail: "open and close the string inside the call" }, { label: "Hello, Mompy!", detail: "the string content that will appear as output" }], mompy: "These are two independent pairs: parentheses delimit the call; quotes delimit the text inside it.", mompyVisible: true, aux: { kind: "reading-animation", action: "print", text: '("Hello, Mompy!")', displayText: '"Hello, Mompy!"', kicker: "READING", actionLabel: "ACTION", textLabel: "TEXT", executeLabel: "⚡ UNDERSTAND FIRST • EXECUTE NEXT", alt: "Complete reading of the print function, parentheses, and quoted string" }, actionLabel: "CODE UNDERSTOOD" },
        { id: "syntax-pairs", phase: "PART 5 · BUILD A COMPLETE PRINT", type: "lesson", title: "Quotes and parentheses work in pairs", body: ["Parentheses open and close the function call. Inside them, quotes open and close the text.", "They are independent pairs: if either one remains open, the instruction is incomplete and Python cannot run it."], code: "print(\"I did it!\")", bullets: ["print — the action name", "( ) — open and close the call", "\" \" — open and close the text"], warning: "Always check both pairs before running: an opening quote needs a closing quote, and an opening parenthesis does too.", mompy: "Check the two pairs separately. When call and text are closed, the instruction is ready to run.", mompyVisible: true, aux: { kind: "pair-animation", code: 'print("I did it!")', kicker: "SYNTAX PAIRS", parenthesesLabel: "PARENTHESES: COMPLETE CALL", quotesLabel: "QUOTES: COMPLETE TEXT", validLabel: "✓ COMPLETE SHAPE", alt: "Parentheses and quotes completing the print instruction in pairs" } },
        { id: "fill-text", phase: "COMPLETE THE INSTRUCTION", type: "choice", title: "Make this appear: I did it!", code: "print(__________)", choices: [{ text: "I did it!", correct: false, code: true }, { text: "print", correct: false, code: true }, { text: "\"I did it!\"", correct: true, code: true }], success: "Right. The quotes tell Python that I did it! is text.", error: "The blank needs to receive complete text.", hint: "Text begins and ends with quotes.", mompyVisible: false, keepAuxDuringQuestion: true, aux: { label: "OUTPUT", value: "?" }, auxSuccess: { label: "OUTPUT", value: "I did it!" } },
        { id: "mastery-python", phase: "FINAL CHECK · 1/5", type: "choice", title: "Which sentence describes Python?", choices: [{ text: "A physical computer part", correct: false }, { text: "A language for writing instructions", correct: true }, { text: "Only a drawing program", correct: false }], success: "Correct.", error: "Python is not a physical part and is not limited to one task.", hint: "Think about how we communicate instructions to a computer.", mompyVisible: false },
        { id: "mastery-print", phase: "FINAL CHECK · 2/5", type: "choice", title: "What does print do?", choices: [{ text: "Displays every word that exists in the code", correct: false }, { text: "Turns every text into a number", correct: false }, { text: "Displays information as output", correct: true }], success: "Correct.", error: "Remember the machine's first answer.", hint: "We use print when we want to see a message or result.", mompyVisible: false },
        { id: "mastery-text", phase: "FINAL CHECK · 3/5", type: "choice", title: "In print(\"Hi\"), which part is the text?", choices: [{ text: "print", correct: false, code: true }, { text: "\"Hi\"", correct: true, code: true }, { text: "( )", correct: false, code: true }], success: "Correct.", error: "Find the content delimited by quotes.", hint: "The quotes surround the text.", mompyVisible: false },
        { id: "mastery-order", phase: "FINAL CHECK · 4/5", type: "choice", title: "What is the output?", code: "print(\"A\")\nprint(\"B\")", choices: [{ text: "A\nB", correct: true, code: true }, { text: "B\nA", correct: false, code: true }, { text: "AB", correct: false, code: true }], success: "Correct.", error: "Read one instruction at a time, from top to bottom.", hint: "Each print creates one output line.", mompyVisible: false },
        { id: "mastery-syntax", phase: "FINAL CHECK · 5/5", type: "choice", title: "Which code is complete?", choices: [{ text: "print(\"Ready)", correct: false, code: true }, { text: "print\"Ready\"", correct: false, code: true }, { text: "print(\"Ready\")", correct: true, code: true }], success: "Check complete.", error: "Check both pairs: quotes and parentheses.", hint: "The complete shape is: action, open parenthesis, quoted text, close parenthesis.", mompyVisible: false },
        { id: "summary", phase: "LESSON COMPLETE", type: "summary", title: "You can already make Python answer", learned: ["Python is a programming language", "the interpreter reads and runs code", "syntax organizes valid writing", "a function is a ready-made action called by name", "print is the function that displays information", "quotes delimit strings", "simple instructions follow an order"], missions: ["transmit messages", "build print correctly", "predict output", "create two lines"], mompy: "You started with Python's origin, followed the interpreter, and reached a complete print call. Now use the missions to prove that every symbol and every line has a purpose.", mompyVisible: true, actionLabel: "GO TO MISSIONS" },
      ],
    },
  },
};
